#!/bin/sh

HOST=$1
BASEDIR=$2
NUM=$3
port=6000
Port=6002
LIBPATH=/home/receptivity/rclib/rclibR1/lib
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi

HOMEDIR=`dirname $0`

teamname="Receptivity"

player="${HOMEDIR}/receptivity/src/sample_player"
coach="${HOMEDIR}/receptivity/src/sample_coach"

config="${HOMEDIR}/receptivity/src/player.conf"
config_dir="${HOMEDIR}/receptivity/src/formations-dt"
coach_config="${HOMEDIR}/receptivity/src/coach.conf"

opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${HOST} -t ${teamname} -p ${port}"

coachopt="--coach-config ${coach_config}"
coachopt="${coachopt} -h ${HOST} -t ${teamname} -P ${Port}"

cd $BASEDIR

case $NUM in
    1)
        $player $opt -g
        ;;
    12)
        $coach $coachopt
        ;;
    *)
        $player $opt
        ;;
esac


