#!/bin/sh

HOST=$1
BASEDIR=$2
NUM=$3
port=6000
Port=6002
LIBPATH=/home/fcpgpr/fcplib/lib
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi

teamname="FCP_GPR_2018NS"

player="/home/fcpgpr/FCP_GPR_2019/src/fcportugal_setplay_player"
coach="/home/fcpgpr/FCP_GPR_2019/src/sample_coach"

config="/home/fcpgpr/FCP_GPR_2019/src/player.conf"
config_dir="/home/fcpgpr/FCP_GPR_2019/src/formations-dt"
coach_config="/home/fcpgpr/FCP_GPR_2019/src/coach.conf"

opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${HOST} -t ${teamname} -p ${port}"

coachopt="--coach-config ${coach_config}"
coachopt="${coachopt} -h ${HOST} -t ${teamname} -P ${Port}"


case $NUM in
    1)
        $player $opt -g
        ;;
    12)
        $coach $coachopt
        ;;
    *)
        $player $opt
        ;;
esac
